apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: own-project
  name: logstash01
  labels:
    name: logstash01
spec:
  replicas: 
  template:
    metadata:
      labels:
        name: logstash01
    spec:
      containers:
      - name: logstash01
        image: 192.168.81.97:5000/logstash:latest
        ports:
        - containerPort: 5043


